
import { Item, Employee, Branch, User, POCustomer, Customer, Driver, Vehicle } from './types';

export const defaultAdmin: User = {
    id: 'admin',
    username: 'admin',
    password: '123',
    role: 'admin',
    permissions: {
        allowedPages: ['Dashboard', 'Daily Sales', 'Monthly Sales', 'Annual Sales', 'Account Statement', 'Invoices Tracking', 'Combined Summary', 'PO', 'Driver Work Log', 'Drivers Timesheet', 'Customers', 'Orders', 'Order Approvals', 'Settings'],
        allowedBranches: ['all'],
        canAddInvoice: true,
        canEditInvoice: true,
        canDeleteInvoice: true,
        canChangeInvoiceDate: true,
        canViewAccountStatement: true,
        canManageSettings: true,
        canCreatePO: true,
        canForceDeletePO: true,
        canEditPO: true,
        canDeletePO: true,
        canEditDriverLog: true,
        canDeleteDriverLog: true,
        manageDrivers: true,
        manageVehicles: true,
        receiveLowPOAlert: true,
        receiveNewOrderAlert: true,
        showDeliveryConfirmationPopup: true,
        showOrderReceiptPopup: true,
        showReceiptDetailsPopup: true
    }
};

export const alaaUser: User = {
    id: 'alaa-hidden',
    username: 'alaa',
    password: '0120301012',
    role: 'admin',
    permissions: {
        allowedPages: ['Dashboard', 'Daily Sales', 'Monthly Sales', 'Annual Sales', 'Account Statement', 'Invoices Tracking', 'Combined Summary', 'PO', 'Driver Work Log', 'Drivers Timesheet', 'Customers', 'Orders', 'Order Approvals', 'Settings'],
        allowedBranches: ['all'],

        canAddInvoice: true,
        canEditInvoice: true,
        canDeleteInvoice: true,
        canChangeInvoiceDate: true,
        canViewAccountStatement: true,
        canManageSettings: true,
        canCreatePO: true,
        canForceDeletePO: true,
        canEditPO: true,
        canDeletePO: true,
        canEditDriverLog: true,
        canDeleteDriverLog: true,
        manageDrivers: true,
        manageVehicles: true,
        receiveLowPOAlert: true,
        receiveNewOrderAlert: true,
        showDeliveryConfirmationPopup: true,
        showOrderReceiptPopup: true,
        showReceiptDetailsPopup: true
    }
};

export const mockItems: Item[] = [
    { id: '1', name: 'Sweet Water', code: '101' },
    { id: '2', name: 'Raw Water', code: '102' },
    { id: '3', name: 'Distil Water', code: '103' },
    { id: '4', name: 'Special water', code: '104' },
    { id: 'cancel', name: 'Cancel', code: '999' },
];

export const mockEmployees: Employee[] = [];

export const mockBranches: Branch[] = [
    { id: 'b3', name: 'Main Branch' },
    { id: 'b1', name: 'Dammam Branch' },
    { id: 'b2', name: 'AlHasa Branch' },
];

export const mockDrivers: Driver[] = [
    { id: 'd1', driverId: 1, driverName: 'MAHANDER' },
    { id: 'd2', driverId: 2, driverName: 'DANESH' },
    { id: 'd3', driverId: 3, driverName: 'SANTRAJ' },
    { id: 'd4', driverId: 4, driverName: 'IMTIAZ' },
    { id: 'd5', driverId: 5, driverName: 'GOMER' },
    { id: 'd6', driverId: 6, driverName: 'MOHEM' },
    { id: 'd7', driverId: 7, driverName: 'SAYEED' },
    { id: 'd8', driverId: 8, driverName: 'KAMAL' },
    { id: 'd9', driverId: 9, driverName: 'SALMAN' },
    { id: 'd10', driverId: 10, driverName: 'ABDULRAHMAN' },
    { id: 'd11', driverId: 11, driverName: 'Many' },
    { id: 'd12', driverId: 12, driverName: 'Nazrull' },
    { id: 'd13', driverId: 13, driverName: 'Harpal Singh' },
    { id: 'd14', driverId: 14, driverName: 'ABDUL SAMAD' },
    { id: 'd15', driverId: 15, driverName: 'SAHIB JAEID' },
    { id: 'd16', driverId: 16, driverName: 'MUSHREF' },
];

export const mockVehicles: Vehicle[] = [
    { id: 'v1', vehicleId: 1, vehicleNumber: '8779 HAS' },
    { id: 'v2', vehicleId: 2, vehicleNumber: '8100 HAS' },
    { id: 'v3', vehicleId: 3, vehicleNumber: '3281 HAS' },
    { id: 'v4', vehicleId: 4, vehicleNumber: '3532 HAS' },
    { id: 'v5', vehicleId: 5, vehicleNumber: '3038 TVB' },
    { id: 'v6', vehicleId: 6, vehicleNumber: '4388 JDJ' },
    { id: 'v7', vehicleId: 7, vehicleNumber: '8727 HAS' },
    { id: 'v8', vehicleId: 8, vehicleNumber: '408 GHD' },
    { id: 'v9', vehicleId: 9, vehicleNumber: '1899 DLJ' },
    { id: 'v10', vehicleId: 10, vehicleNumber: '3037 TVB' },
    { id: 'v11', vehicleId: 11, vehicleNumber: '3931 HAS' },
    { id: 'v12', vehicleId: 12, vehicleNumber: '8565 HAS' },
    { id: 'v13', vehicleId: 13, vehicleNumber: '3529 HAS' },
    { id: 'v14', vehicleId: 14, vehicleNumber: '9946 REA' },
    { id: 'v15', vehicleId: 15, vehicleNumber: '9947 REA' },
    { id: 'v16', vehicleId: 16, vehicleNumber: '3628 HAS' },
    { id: 'v17', vehicleId: 17, vehicleNumber: '2282 BXA' },
    { id: 'v18', vehicleId: 18, vehicleNumber: '8669 HAS' },
    { id: 'v19', vehicleId: 19, vehicleNumber: '3646 HAS' },
    { id: 'v20', vehicleId: 20, vehicleNumber: '8778 HAS' },
    { id: 'v21', vehicleId: 21, vehicleNumber: '4902 RXA' },
    { id: 'v22', vehicleId: 22, vehicleNumber: '2978 BXA' },
    { id: 'v23', vehicleId: 23, vehicleNumber: '1765 BXA' },
    { id: 'v24', vehicleId: 24, vehicleNumber: '4300 UXA' },
];

export const mockPOCustomers: POCustomer[] = [
    {
        id: 'po-1',
        customerNumber: 'C001',
        customerName: 'Ahmad Sales Co',
        poNumber: 'PO-2024-001',
        type: 'credit',
        quantity: 1000,
        total: 5000,
    },
    {
        id: 'po-2',
        customerNumber: 'C002',
        customerName: 'Gulf Trading',
        poNumber: 'PO-2024-002',
        type: 'credit',
        quantity: 500,
        total: 2500,
    },
];

export const mockCustomers: Customer[] = [
    { id: 'c-7', customerNumber: '110201007', name: 'ELSALAMAH RADIATORS FACT' },
    { id: 'c-8', customerNumber: '110201008', name: 'NATIONAL ROAD STUD' },
    { id: 'c-14', customerNumber: '110201014', name: 'SIGMA PAINTS' },
    { id: 'c-16', customerNumber: '110201016', name: 'SAPIN -- VAT NO 300504358400003' },
    { id: 'c-27', customerNumber: '110201027', name: 'Khwatem Almalki Trading EST' },
    { id: 'c-271', customerNumber: '110201271', name: 'Khwatem Almalki Trading EST' },
    { id: 'c-31', customerNumber: '110201031', name: 'National Pioneers Contracting Co' },
    { id: 'c-32', customerNumber: '110201032', name: 'FOUZ CHEMICALES CO' },
    { id: 'c-39', customerNumber: '110201039', name: 'REZAYAT TRADING. CO. LTD' },
    { id: 'c-40', customerNumber: '110201040', name: 'FOUR WINDS' },
    { id: 'c-41', customerNumber: '110201041', name: 'ALI REZA DELTA' },
    { id: 'c-46', customerNumber: '110201046', name: 'INTERNATIONAL INDIAN SCHOOL' },
    { id: 'c-56', customerNumber: '110201056', name: 'WESCOSA' },
    { id: 'c-59', customerNumber: '110201059', name: 'BAKER PETROLITE SAUDI CO. LTD' },
    { id: 'c-67', customerNumber: '110201067', name: 'ALTAMIMI COMPANY' },
    { id: 'c-671', customerNumber: '110201671', name: 'ALTAMIMI COMPANY 1' },
    { id: 'c-73', customerNumber: '110201073', name: 'ALOTABI SILENCERS' },
    { id: 'c-81', customerNumber: '110201081', name: 'Zamil Ship Building & Repair Co. Ltd' },
    { id: 'c-103', customerNumber: '110201103', name: 'المذاق المغربي لتقديم المشروبات' },
    { id: 'c-104', customerNumber: '110201104', name: 'YUSUF BIN AHMED KANOO Co.' },
    { id: 'c-106', customerNumber: '110201106', name: 'شركة سابيم طاقة الرشيد للتصنيع المحدودة - ستار STAR' },
    { id: 'c-115', customerNumber: '110201115', name: 'شركة مصنع الزامل للطلاء الصناعي المحدودة' },
    { id: 'c-119', customerNumber: '110201119', name: 'شركة الترا للخدمات الصناعية' },
    { id: 'c-131', customerNumber: '110201131', name: 'Al-Omear Company' },
    { id: 'c-133', customerNumber: '110201133', name: 'ركة الخدمات المساندة المحدودة(هامارد)' },
    { id: 'c-140', customerNumber: '110201140', name: 'الشركة العربية للخدمات الزراعية (اراسكو )' },
    { id: 'c-143', customerNumber: '110201143', name: 'شركة فيدكو للإستثمار مساهمة مقفلة بالورقة Feedco' },
    { id: 'c-148', customerNumber: '110201148', name: 'نادي القادسية الرياضي Qadisiyah Club' },
    { id: 'c-151', customerNumber: '110201151', name: 'بوند المطلق - Almutlaq Compound' },
    { id: 'c-152', customerNumber: '110201152', name: 'شركة مجموعة الزامل العقارية المحدودة.' },
    { id: 'c-153', customerNumber: '110201153', name: 'Landmark arabia Company - port 1' },
    { id: 'c-154', customerNumber: '110201154', name: 'Landmark arabia Company - port 2' },
    { id: 'c-155', customerNumber: '110201155', name: 'شركة مورجانتي العربية السعودية المحدودة' },
    { id: 'c-156', customerNumber: '110201156', name: 'Snamprogetti Saudi Arabia Co. Ltd.' },
    { id: 'c-162', customerNumber: '110201162', name: 'Maersk Arabia Logistics Services.' },
    { id: 'c-163', customerNumber: '110201163', name: 'فرع شركة الخدمات البحرية العالمية مساهمة مقفلة' },
    { id: 'c-165001', customerNumber: '110201165001', name: 'Enpro Saudi Arabia Ltd' },
    { id: 'c-165004', customerNumber: '110201165004', name: 'مؤسسة بختان التجارية' },
    { id: 'c-165005', customerNumber: '110201165005', name: 'مؤسسة اركان يثرب للنقليات' },
    { id: 'c-165009', customerNumber: '110201165009', name: 'Score Arabia' },
    { id: 'c-165019', customerNumber: '110201165019', name: 'مؤسسة الشهم الوفي للمقاولات المعمارية العامة' },
    { id: 'c-166', customerNumber: '110201166', name: 'Racking System Logistics Services Co.' },
    { id: 'c-169', customerNumber: '110201169', name: 'Branch of China Harbour Engineering Co. LTD' },
    { id: 'c-170', customerNumber: '110201170', name: 'شركة فال العربية المحدودة' },
    { id: 'c-172', customerNumber: '110201172', name: 'مصنع شركة عبد العزيز و سعد المعجل للأعلاف' },
    { id: 'c-173', customerNumber: '110201173', name: 'شركة الخماسية للأعلاف والانتاج الحيواني' },
    { id: 'c-175', customerNumber: '110201175', name: 'شركة مجموعة الزامل للتجارة والخدمات' },
    { id: 'c-176', customerNumber: '110201176', name: 'شركة تسويق و توزيع المواد الكيميائية المحدودة' },
    { id: 'c-177', customerNumber: '110201177', name: 'TechniCompanypFMC' },
    { id: 'c-178', customerNumber: '110201178', name: 'شركة ادنوك الخليج للتوزيع المحدودة' },
    { id: 'c-179', customerNumber: '110201179', name: 'شركة منتجات البلاستيك السعودية المحدودة - كوبونات' },
    { id: 'c-180', customerNumber: '110201180', name: 'شركة أطلس الأفضل للتجارة والمقاولات' },
    { id: 'c-182', customerNumber: '110201182', name: 'مصنع السلامة للصناعات الهندسية' },
    { id: 'c-183', customerNumber: '110201183', name: 'MEDLOG SAUDI Arabia company limited' },
    { id: 'c-184', customerNumber: '110201184', name: 'شركة سنابل الخير للتطوير و الاستثمار العقاري' },
    { id: 'c-187', customerNumber: '110201187', name: 'Gas Metal Tech Co.' },
    { id: 'c-188', customerNumber: '110201188', name: 'شركة الابتكار البحرية المحدودة' },
    { id: 'c-190', customerNumber: '110201190', name: 'شركة رابيد العربيه السعودية المحدودة' },
    { id: 'c-192', customerNumber: '110201192', name: 'شركة سما للتقنيات المحدودة' },
    { id: 'c-193', customerNumber: '110201193', name: 'Kasktas Arabia LTD' },
    { id: 'c-194', customerNumber: '110201194', name: 'شركة شينكر العربية السعودية المحدودة' },
    { id: 'c-195', customerNumber: '110201195', name: 'شركة دار اليوم للصحافة و الطباعة و النشر ACC' },
    { id: 'c-196', customerNumber: '110201196', name: 'شركة ارامكس السعودية المحدودة' },
    { id: 'c-197', customerNumber: '110201197', name: 'شركة الجميح للمرطبات المحدودة' },
    { id: 'c-198', customerNumber: '110201198', name: 'Saudi New Zealand Milk Products' },
    { id: 'c-200', customerNumber: '110201200', name: 'شركة ساحل الشرق لخدمات الموانئ' },
    { id: 'c-201', customerNumber: '110201201', name: 'شركة ناغي للأعمال البحرية' },
    { id: 'c-202', customerNumber: '110201202', name: 'Ess Al-Riyadeh' },
    { id: 'c-203', customerNumber: '110201203', name: 'مصنع سماء المنتجات للكيماويات' },
    { id: 'c-204', customerNumber: '110201204', name: 'شركة تسويق و توزيع المواد الكيميائية المحدودة(الجبيل)' },
    { id: 'c-205', customerNumber: '110201205', name: 'China Railway Construction Corporation Limited' },
    { id: 'c-206', customerNumber: '110201206', name: 'شركة هادي حمد آل همام للمقاولات' },
    { id: 'c-207', customerNumber: '110201207', name: 'الشركة الدولية للنقل المشترك' },
    { id: 'c-208', customerNumber: '110201208', name: 'شركة خدمات اساد المحدودة' },
];
